# Generated by Django 5.2 on 2025-05-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('shipping', 'Shipping'), ('billing', 'Billing')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
