# Generated by Django 5.2 on 2025-05-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_address_created_at_alter_address_address_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
