# Generated by Django 5.2 on 2025-06-17 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date_created',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='order.order'),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
