# Generated by Django 5.2 on 2025-05-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_image',
            field=models.ImageField(null=True, upload_to='categories/'),
        ),
    ]
