# Generated by Django 5.2 on 2025-05-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_price_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_ar',
            field=models.CharField(blank=True, help_text='Enter brand name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_en',
            field=models.CharField(blank=True, help_text='Enter brand name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ar',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='use_and_care_ar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='use_and_care_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_name_ar',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='key_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='key_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='value_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='value_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
