# Generated by Django 5.2 on 2025-05-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productvariantimage_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantimage',
            name='public_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
