# Generated by Django 5.2 on 2025-05-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productvariantimage_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantimage',
            name='is_degault',
            field=models.BooleanField(default=False),
        ),
    ]
