# Generated by Django 5.2 on 2025-05-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productvariantimage_is_degault'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariantimage',
            old_name='is_degault',
            new_name='is_default',
        ),
    ]
