# Generated by Django 5.2 on 2025-06-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productvariant_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter discount as a percentage (e.g., 20 for 20%)', max_digits=5),
        ),
    ]
