# Generated by Django 5.2 on 2025-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productvariant_discount_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_ar',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='only_one_default_variant_per_product'),
        ),
    ]
