# Generated by Django 5.2 on 2025-06-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_is_available_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='ecoco', help_text='Enter brand name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_ar',
            field=models.CharField(blank=True, default='ecoco', help_text='Enter brand name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_en',
            field=models.CharField(blank=True, default='ecoco', help_text='Enter brand name', max_length=100, null=True),
        ),
    ]
