# Generated by Django 5.2 on 2025-06-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productvariant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
